version: 15
ingest:
    input:
        # Servers which provides input data
        # TODO Add support for webdav protocol
        # Use file:// as first element in list when using local data
        servers:
            - https://ccnetlsst10.in2p3.fr:65101
            - https://ccnetlsst11.in2p3.fr:65101
            - https://ccnetlsst12.in2p3.fr:65101
        # Path on server where input data is available
        path: dc2_object_run2_2i_dr6_wfd/
    qserv:

        # URL of Qserv services
        # Proxy URL
        query_url: "mysql://qsmaster:@qserv-czar:4040"
        # Ingest database URL
        queue_url: "mysql://qsingest:@qserv-ingest-db-0.qserv-ingest-db/qservIngest"
        # Replication service URL
        replication_url: http://qserv-repl-ctl-0.qserv-repl-ctl:8080
